name: Events Demo 1
#Adding pull_request with Activity Types. This workflow runs only a pull request is opened
#Adding workflow_dispatch to manually trigger this workflow
on:
  pull_request:
    types: opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."